from turtle import *


speed(0)
def ground():
    color('forest green')
    pensize(2)
    begin_fill()
    forward(200)
    right(90)
    forward(200)
    right(90)
    forward(400)
    right(90)
    forward(200)
    right(90)
    forward(200)
    end_fill()
    
    

def sky():
    color('dim gray')
    pensize(2)
    begin_fill()
    forward(200)
    left(90)
    forward(300)
    left(90)
    forward(400)
    left(90)
    forward(300)
    left(90)
    forward(200)
    end_fill()



def moon():
    pensize(2)
    color('silver')
    penup()
    goto(130, 160)
    pendown()
    begin_fill()
    circle(50)
    end_fill()
    color('white smoke')
    penup()
    goto(115, 170)
    pendown()
    circle(10)
    penup()
    goto(155, 215)
    pendown()
    circle(8)
    penup()
    goto(130, 230)
    pendown()
    circle(12)
    penup()
    goto(105, 200)
    pendown()
    circle(15)
    penup()
    goto(150, 175)
    pendown()
    circle(15)

def clouds1():
    color('gray')
    penup()
    goto(-70, 200)
    pendown()
    begin_fill()
    circle(25)
    end_fill()
    penup()
    goto(-40, 180)
    pendown()
    begin_fill()
    circle(25)
    end_fill()
    penup()
    goto(-30, 210)
    pendown()
    begin_fill()
    circle(30)
    end_fill()
    penup()
    goto(-10, 190)
    pendown()
    begin_fill()
    circle(20)
    end_fill()

def clouds2():
    color('gray')
    penup()
    goto(-170, 200)
    pendown()
    begin_fill()
    circle(30)
    end_fill()
    penup()
    goto(-140, 180)
    pendown()
    begin_fill()
    circle(30)
    end_fill()
    penup()
    goto(-130, 210)
    pendown()
    begin_fill()
    circle(35)
    end_fill()
    penup()
    goto(-110, 190)
    pendown()
    begin_fill()
    circle(25)
    end_fill()

def road():
    color('black')
    penup()
    goto(0, -150)
    pendown()
    begin_fill()
    forward(200)
    right(90)
    forward(50)
    right(90)
    forward(400)
    right(90)
    forward(50)
    right(90)
    forward(200)
    end_fill()
    #road_lines
    penup()
    goto(-190, -190)
    pendown()
    color('white')
    begin_fill()
    forward(50)
    right(120)
    forward(5)
    right(60)
    forward(50)
    right(120)
    forward(5)
    right(60)
    end_fill()
    penup()
    forward(100)
    pendown()
    begin_fill()
    forward(50)
    right(120)
    forward(5)
    right(60)
    forward(50)
    right(120)
    forward(5)
    right(60)
    end_fill()
    penup()
    forward(100)
    pendown()
    begin_fill()
    forward(50)
    right(120)
    forward(5)
    right(60)
    forward(50)
    right(120)
    forward(5)
    right(60)
    end_fill()
    penup()
    forward(100)
    pendown()
    begin_fill()
    forward(50)
    right(120)
    forward(5)
    right(60)
    forward(50)
    right(120)
    forward(5)
    right(60)
    end_fill()
    penup()
    forward(100)
    pendown()
    begin_fill()
    forward(50)
    right(120)
    forward(5)
    right(60)
    forward(50)
    right(120)
    forward(5)
    right(60)
    end_fill()

def pedestrian_walk():
    penup()
    goto(0, -150)
    pendown()
    color('light gray')
    begin_fill()
    forward(200)
    left(90)
    forward(30)
    left(90)
    forward(400)
    left(90)
    forward(30)
    left(90)
    forward(200)
    end_fill()

def office_buildings():
    #ground
    color('dark gray')
    penup()
    goto(-170, -80)
    pendown()
    begin_fill()
    forward(100)
    left(45)
    forward(60)
    left(135)
    forward(100)
    left(45)
    forward(60)
    end_fill()
    #forwards_part
    right(135)
    forward(180)
    penup()
    goto(-29, -40)
    pendown()
    forward(180)
    penup()
    goto(-127, -37)
    pendown()
    forward(180)
    penup()
    goto(-70, -80)
    pendown()
    begin_fill()
    forward(180)
    left(90)
    forward(100)
    left(90)
    forward(180)
    left(90)
    forward(100)
    end_fill()
    #leftpart(visiblewall)
    color('gainsboro')
    begin_fill()
    left(45)
    forward(60)
    left(45)
    forward(180)
    left(135)
    forward(60)
    left(45)
    forward(180)
    end_fill()
    color('dark gray')
    #rightpart(nonvisiblewall)
    penup()
    goto(-127, 144)
    pendown()
    begin_fill()
    forward(180)
    right(45)
    forward(60)
    right(135)
    forward(180)
    right(45)
    forward(60)
    end_fill()
    #topwall
    color('silver')
    begin_fill()
    right(45)
    forward(100)
    right(135)
    forward(60)
    right(45)
    forward(100)
    right(135)
    forward(60)
    end_fill()
    #door(on forwards_part)
    right(45)
    color('saddle brown')
    penup()
    goto(-135, -75)
    pendown()
    begin_fill()
    forward(30)
    left(90)
    forward(50)
    left(90)
    forward(30)
    left(90)
    forward(50)
    end_fill()
    #handle(on door)
    left(90)
    color('yellow')
    penup()
    goto(-110, -55)
    pendown()
    begin_fill()
    circle(2)
    end_fill()
    #windows(on forwards_part)
    penup()
    goto(-160, 90)
    pendown()
    begin_fill()
    forward(30)
    right(90)
    forward(45)
    right(90)
    forward(30)
    right(90)
    forward(45)
    right(90)
    end_fill()
    penup()
    goto(-115, 90)
    pendown()
    color('black')
    begin_fill()
    forward(30)
    right(90)
    forward(45)
    right(90)
    forward(30)
    right(90)
    forward(45)
    end_fill()
    color('yellow')
    penup()
    goto(-160, -15)
    pendown()
    begin_fill()
    forward(45)
    right(90)
    forward(30)
    right(90)
    forward(45)
    right(90)
    forward(30)
    right(90)
    end_fill()
    penup()
    goto(-115, -15)
    pendown()
    begin_fill()
    forward(45)
    right(90)
    forward(30)
    right(90)
    forward(45)
    right(90)
    forward(30)
    right(90)
    end_fill()
    #finishing_parts
    color('dark gray')
    penup()
    goto(-70, -80)
    pendown()
    forward(180)
    right(90)

def lights1():
    #base_lamp
    color('gray')
    penup()
    goto(-180, -140)
    pendown()
    begin_fill()
    forward(40)
    left(120)
    forward(20)
    left(60)
    forward(20)
    left(60)
    forward(20)
    end_fill()
    color('black')
    left(120)
    forward(15)
    left(90)
    #pole_lamp
    color('dim gray')
    begin_fill()
    forward(80)
    right(90)
    forward(10)
    right(90)
    forward(80)
    right(90)
    forward(10)
    end_fill()
    right(90)
    forward(80)
    #top_lamp
    color('dim gray')
    begin_fill()
    right(90)
    forward(30)
    left(180)
    forward(55)
    right(135)
    forward(30)
    right(45)
    forward(15)
    right(45)
    forward(30)
    right(135)
    forward(55)
    end_fill()
    right(180)
    #finishing_parts
    color('gray')
    penup()
    goto(-180, -140)
    pendown()
    begin_fill()
    forward(40)
    left(120)
    forward(20)
    left(60)
    forward(20)
    left(60)
    forward(20)
    end_fill()
    color('gray')
    left(120)
    forward(15)
    left(90)
    forward(10)
    color('dim gray')
    begin_fill()
    forward(20)
    right(90)
    forward(10)
    right(90)
    forward(20)
    right(90)
    forward(10)
    end_fill()
    right(90)
    forward(70)
    left(90)
    #lamp_light
    color('khaki')
    begin_fill()
    forward(10)
    right(180)
    right(45)
    forward(10)
    left(45)
    forward(15)
    left(45)
    forward(10)
    left(135)
    forward(30)
    right(180)
    forward(30)
    end_fill()

def lights2():
    #base_lamp
    color('gray')
    penup()
    goto(-20, -140)
    pendown()
    begin_fill()
    forward(40)
    left(120)
    forward(20)
    left(60)
    forward(20)
    left(60)
    forward(20)
    end_fill()
    color('black')
    left(120)
    forward(15)
    left(90)
    #pole_lamp
    color('dim gray')
    begin_fill()
    forward(80)
    right(90)
    forward(10)
    right(90)
    forward(80)
    right(90)
    forward(10)
    end_fill()
    right(90)
    forward(80)
    #top_lamp
    color('dim gray')
    begin_fill()
    right(90)
    forward(30)
    left(180)
    forward(55)
    right(135)
    forward(30)
    right(45)
    forward(15)
    right(45)
    forward(30)
    right(135)
    forward(55)
    end_fill()
    right(180)
    #finishing_parts
    color('gray')
    penup()
    goto(-20, -140)
    pendown()
    begin_fill()
    forward(40)
    left(120)
    forward(20)
    left(60)
    forward(20)
    left(60)
    forward(20)
    end_fill()
    color('gray')
    left(120)
    forward(15)
    left(90)
    forward(10)
    color('dim gray')
    begin_fill()
    forward(20)
    right(90)
    forward(10)
    right(90)
    forward(20)
    right(90)
    forward(10)
    end_fill()
    right(90)
    forward(70)
    left(90)
    #lamp_light
    color('khaki')
    begin_fill()
    forward(10)
    right(180)
    right(45)
    forward(10)
    left(45)
    forward(15)
    left(45)
    forward(10)
    left(135)
    forward(30)
    right(180)
    forward(30)
    end_fill()

def lights3():
    #base_lamp
    color('gray')
    penup()
    goto(140, -140)
    pendown()
    begin_fill()
    forward(40)
    left(120)
    forward(20)
    left(60)
    forward(20)
    left(60)
    forward(20)
    end_fill()
    color('black')
    left(120)
    forward(15)
    left(90)
    #pole_lamp
    color('dim gray')
    begin_fill()
    forward(80)
    right(90)
    forward(10)
    right(90)
    forward(80)
    right(90)
    forward(10)
    end_fill()
    right(90)
    forward(80)
    #top_lamp
    color('dim gray')
    begin_fill()
    right(90)
    forward(30)
    left(180)
    forward(55)
    right(135)
    forward(30)
    right(45)
    forward(15)
    right(45)
    forward(30)
    right(135)
    forward(55)
    end_fill()
    right(180)
    #finishing_parts
    color('gray')
    penup()
    goto(140, -140)
    pendown()
    begin_fill()
    forward(40)
    left(120)
    forward(20)
    left(60)
    forward(20)
    left(60)
    forward(20)
    end_fill()
    color('gray')
    left(120)
    forward(15)
    left(90)
    forward(10)
    color('dim gray')
    begin_fill()
    forward(20)
    right(90)
    forward(10)
    right(90)
    forward(20)
    right(90)
    forward(10)
    end_fill()
    right(90)
    forward(70)
    left(90)
    #lamp_light
    color('khaki')
    begin_fill()
    forward(10)
    right(180)
    right(45)
    forward(10)
    left(45)
    forward(15)
    left(45)
    forward(10)
    left(135)
    forward(30)
    right(180)
    forward(30)
    end_fill()


hideturtle()
